org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttp.connectionTimeout=120000 -Dhttp.socketTimeout=120000
org.gradle.daemon=false
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
android.useAndroidX=true
kotlin.code.style=official
android.aapt2FromMavenOverride=/data/openclaw/opt/android-sdk/build-tools/36.0.0/aapt2
